// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehzdbgbzwgipzzpsswsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoemRiZ2J6d2dpcHp6cHNzd3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTQzNzIsImV4cCI6MjA2MjQ5MDM3Mn0.3Fe9lflA7v_eUvBReE_MdIOVF52h19Fsz85ME0FR-QE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);