// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilpabulrohyiztvbfxmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlscGFidWxyb2h5aXp0dmJmeG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Nzk5MjIsImV4cCI6MjA2MjA1NTkyMn0.oH1Hi2qKD3tr4WsADN3Y7IO6RLvPPjVCMr7dlBcNQYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);